version: '3.8'

services:
  db_test:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER_TESTING}
      - POSTGRES_PASSWORD=${DB_PASSWORD_TESTING}
      - POSTGRES_DB=${DB_NAME_TESTING}
    ports:
      - "5432:5433"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d y_lab_fastapi_test"]
      interval: 10s
      timeout: 5s
      retries: 5

  
  test_web_2_app:
    container_name: test_2_app
    build:
      context: .
      dockerfile: Dockerfile
    command: pytest -vv tests/tester_menu.py #uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8080 && 
    volumes:
      - .:/app
    environment:
      - DB_USER=${DB_USER_TESTING}
      - DB_PASSWORD=${DB_PASSWORD_TESTING}
      - DB_NAME=${DB_NAME_TESTING}
      - DB_PORT=${DB_PORT_TESTING}
      - SQLALCHEMY_SILENCE_UBER_WARNING=1
    ports:
      - "8080:8080"
    depends_on:
      db_test:
        condition: service_healthy
